TARGET	= libmatmult.so
LIBSRCS	= 
LIBOBJS	= 

OPT	= -g 
PIC	= -fPIC

CXX	= sunCC
CXXFLAGS= $(OPT) $(PIC) $(XOPTS)

SOFLAGS = -shared 
XLIBS	= 

$(TARGET): $(LIBOBJS)
	$(CXX) -o $@ $(SOFLAGS) $(LIBOBJS) $(XLIBS)

clean:
	@/bin/rm -f core core.* $(LIBOBJS) 
